# https://circleci.com/blog/circleci-config-teardown-how-we-write-our-circleci-config-at-circleci/
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      - run: ./docker_build.sh

